pub const CANONICAL_SERVICE_PATTERNS: &[(&str, &[&str])] = &[
    ("openai", &["openai", "chatgpt", "gpt"]),
    ("apple", &["apple", "wx"]),
    ("aol", &["aol", "pm"]),
    ("discord", &["discord", "ds"]),
    ("google chat", &["google chat", "ccu", "ght"]),
    ("microsoft", &["microsoft", "mm"]),
    ("telegram", &["telegram", "tg"]),
    ("twitter", &["twitter", "twitter x", "tw"]),
    ("uber", &["uber", "ub"]),
    ("wechat", &["wechat", "wb"]),
    ("yahoo", &["yahoo", "mb"]),
    ("telegram", &["telegram", "tg"]),
    ("whatsapp", &["whatsapp", "whatsapp business", "wa"]),
    ("paypal", &["paypal"]),
    ("claude", &["claude", "anthropic", "claudeai"]),
];

pub const CANONICAL_COUNTRY_TEXT_ALIASES: &[(&str, &[&str])] = &[
    ("any", &["any", "all countries", "auto select"]),
    ("local", &["local"]),
    ("usa", &["usa", "united states", "united states virtual", "america"]),
    ("uk", &["england", "uk", "united kingdom", "britain"]),
    ("germany", &["germany", "deutschland"]),
    ("japan", &["japan"]),
    ("canada", &["canada"]),
    ("australia", &["australia", "australia virtual"]),
    ("russia", &["russia", "россия", "russian federation"]),
    ("argentina", &["argentina", "argentinas"]),
    ("vietnam", &["vietnam", "viet nam"]),
    ("southafrica", &["south africa"]),
    ("bosnia and herzegovina", &["bosnia and herzegovina", "bih"]),
    ("trinidad and tobago", &["trinidad and tobago"]),
    ("czech republic", &["czech republic", "czechia"]),
    ("north macedonia", &["north macedonia"]),
    ("south korea", &["south korea"]),
    ("north korea", &["north korea"]),
    ("jordan", &["jordan"]),
];

pub const CANONICAL_SERVICE_LABELS: &[(&str, &str)] = &[
    ("apple", "Apple"),
    ("aol", "AOL"),
    ("discord", "Discord"),
    ("google chat", "Google Chat"),
    ("microsoft", "Microsoft"),
    ("openai", "OpenAI (GPT)"),
    ("claude", "Claude"),
    ("telegram", "Telegram"),
    ("twitter", "Twitter/X"),
    ("uber", "Uber"),
    ("wechat", "WeChat"),
    ("whatsapp", "WhatsApp"),
    ("paypal", "PayPal"),
    ("yahoo", "Yahoo"),
];

pub const CANONICAL_COUNTRY_LABELS: &[(&str, &str)] = &[
    ("any", "All countries"),
    ("local", "Local"),
    ("usa", "United States"),
    ("uk", "United Kingdom"),
    ("germany", "Germany"),
    ("japan", "Japan"),
    ("canada", "Canada"),
    ("australia", "Australia"),
    ("russia", "Russia"),
    ("argentina", "Argentina"),
    ("vietnam", "Vietnam"),
    ("southafrica", "South Africa"),
    ("bosnia and herzegovina", "Bosnia and Herzegovina"),
    ("trinidad and tobago", "Trinidad and Tobago"),
    ("czech republic", "Czech Republic"),
    ("north macedonia", "North Macedonia"),
    ("south korea", "South Korea"),
    ("north korea", "North Korea"),
    ("jordan", "Jordan"),
];
