pub const CANONICAL_SERVICE_PATTERNS: &[(&str, &[&str])] = &[
    ("openai", &["openai", "chatgpt", "gpt"]),
    ("apple", &["apple", "wx"]),
    ("aol", &["aol", "pm"]),
    ("discord", &["discord", "ds"]),
    ("google chat", &["google chat", "ccu", "ght"]),
    ("microsoft", &["microsoft", "mm"]),
    ("telegram", &["telegram", "tg"]),
    ("twitter", &["twitter", "twitter x", "tw"]),
    ("uber", &["uber", "ub"]),
    ("wechat", &["wechat", "wb"]),
    ("yahoo", &["yahoo", "mb"]),
    ("telegram", &["telegram", "tg"]),
    ("whatsapp", &["whatsapp", "whatsapp business", "wa"]),
    ("paypal", &["paypal"]),
    ("claude", &["claude", "anthropic", "claudeai"]),
];

pub const CANONICAL_COUNTRY_TEXT_ALIASES: &[(&str, &[&str])] = &[
    ("any", &["any", "all countries", "auto select"]),
    ("local", &["local"]),
    ("usa", &["usa", "united states", "united states virtual", "america"]),
    ("uk", &["england", "uk", "united kingdom", "britain"]),
    ("china", &["china"]),
    ("bahrain", &["bahrain", "巴林"]),
    ("bermuda", &["bermuda", "百慕大"]),
    ("cape verde", &["cape verde", "佛得角"]),
    ("denmark", &["denmark", "丹麥"]),
    ("eritrea", &["eritrea", "厄立特里亞"]),
    ("fiji", &["fiji", "斐濟"]),
    ("gibraltar", &["gibraltar", "直布罗陀"]),
    ("germany", &["germany", "deutschland"]),
    ("jordan", &["jordan", "約旦"]),
    ("japan", &["japan"]),
    ("canada", &["canada"]),
    ("australia", &["australia", "australia virtual"]),
    ("liechtenstein", &["liechtenstein", "列支敦士登"]),
    ("maldives", &["maldives", "马尔代夫"]),
    ("malta", &["malta", "马耳他"]),
    ("monaco", &["monaco", "摩納哥"]),
    ("montenegro", &["montenegro", "黑山共和国"]),
    ("montserrat", &["montserrat", "蒙特塞拉特"]),
    ("new caledonia", &["new caledonia", "新喀裡多尼亞"]),
    ("niue", &["niue", "纽埃"]),
    ("north macedonia", &["north macedonia", "北馬其頓"]),
    ("norway", &["norway", "挪威"]),
    ("palestine", &["palestine", "巴勒斯坦"]),
    ("russia", &["russia", "россия", "russian federation"]),
    ("argentina", &["argentina", "argentinas"]),
    ("aruba", &["aruba", "阿魯巴島"]),
    ("anguilla", &["anguilla", "安圭拉島"]),
    ("vietnam", &["vietnam", "viet nam"]),
    ("samoa", &["samoa", "萨摩亚"]),
    ("sao tome and principe", &["sao tome and principe", "聖多美和普林西比"]),
    ("seychelles", &["seychelles", "塞舌爾共和國"]),
    ("solomon islands", &["solomon islands", "所罗门群岛"]),
    ("south sudan", &["south sudan", "南蘇丹"]),
    ("southafrica", &["south africa"]),
    ("bosnia and herzegovina", &["bosnia and herzegovina", "bih"]),
    ("switzerland", &["switzerland", "瑞士"]),
    ("tonga", &["tonga", "汤加王国"]),
    ("trinidad and tobago", &["trinidad and tobago"]),
    ("turkmenistan", &["turkmenistan", "土库曼斯坦"]),
    ("czech republic", &["czech republic", "czechia"]),
    ("hong kong", &["hong kong"]),
    ("jersey", &["jersey", "泽西岛"]),
    ("kosovo", &["kosovo", "科索沃"]),
    ("singapore", &["singapore"]),
    ("singapore", &["new singapore republic", "新加坡共和国"]),
    ("ukraine", &["ukraine"]),
    ("south korea", &["south korea"]),
    ("south korea", &["大韓民國"]),
    ("north korea", &["north korea"]),
    ("north korea", &["朝鲜民主主义人民共和国"]),
    ("western sahara", &["western sahara", "撒哈拉沙漠西部"]),
];

pub const CANONICAL_SERVICE_LABELS: &[(&str, &str)] = &[
    ("apple", "Apple"),
    ("aol", "AOL"),
    ("discord", "Discord"),
    ("google chat", "Google Chat"),
    ("microsoft", "Microsoft"),
    ("openai", "OpenAI (GPT)"),
    ("claude", "Claude"),
    ("telegram", "Telegram"),
    ("twitter", "Twitter/X"),
    ("uber", "Uber"),
    ("wechat", "WeChat"),
    ("whatsapp", "WhatsApp"),
    ("paypal", "PayPal"),
    ("yahoo", "Yahoo"),
];

pub const CANONICAL_COUNTRY_LABELS: &[(&str, &str)] = &[
    ("any", "All countries"),
    ("local", "Local"),
    ("usa", "United States"),
    ("uk", "United Kingdom"),
    ("anguilla", "Anguilla"),
    ("aruba", "Aruba"),
    ("bahrain", "Bahrain"),
    ("bermuda", "Bermuda"),
    ("cape verde", "Cape Verde"),
    ("china", "China"),
    ("denmark", "Denmark"),
    ("eritrea", "Eritrea"),
    ("fiji", "Fiji"),
    ("gibraltar", "Gibraltar"),
    ("germany", "Germany"),
    ("japan", "Japan"),
    ("jersey", "Jersey"),
    ("kosovo", "Kosovo"),
    ("canada", "Canada"),
    ("australia", "Australia"),
    ("liechtenstein", "Liechtenstein"),
    ("maldives", "Maldives"),
    ("malta", "Malta"),
    ("monaco", "Monaco"),
    ("montenegro", "Montenegro"),
    ("montserrat", "Montserrat"),
    ("new caledonia", "New Caledonia"),
    ("niue", "Niue"),
    ("russia", "Russia"),
    ("argentina", "Argentina"),
    ("norway", "Norway"),
    ("palestine", "Palestine"),
    ("samoa", "Samoa"),
    ("sao tome and principe", "Sao Tome and Principe"),
    ("seychelles", "Seychelles"),
    ("solomon islands", "Solomon Islands"),
    ("south sudan", "South Sudan"),
    ("vietnam", "Vietnam"),
    ("southafrica", "South Africa"),
    ("bosnia and herzegovina", "Bosnia and Herzegovina"),
    ("switzerland", "Switzerland"),
    ("tonga", "Tonga"),
    ("trinidad and tobago", "Trinidad and Tobago"),
    ("turkmenistan", "Turkmenistan"),
    ("czech republic", "Czech Republic"),
    ("north macedonia", "North Macedonia"),
    ("hong kong", "Hong Kong"),
    ("singapore", "Singapore"),
    ("ukraine", "Ukraine"),
    ("south korea", "South Korea"),
    ("north korea", "North Korea"),
    ("western sahara", "Western Sahara"),
    ("jordan", "Jordan"),
];
